### ISSUE TITLE
Append only the required lines

### ISSUE THREAD

**Issue by mhoshi-vm** [hirokim-vm/tpk8s-tkgm-istio-overlays#1]
Currently we are replacing the entire configmap.
Using ytt and lambda expression we should be able to only append the required lines.

**Comment by mhoshi-vm** [comment]
Haven't tested but I think this would work. This would only append `enableTracing: true` and would not touch anything else.

```

apiVersion: v1
kind: Secret
metadata:
  name: tcs-overlay
type: Opaque
stringData:
  overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")

    #@ def custom_config():
    #@overlay/match missing_ok=True
    #@overlay/match-child-defaults missing_ok=True
    enableTracing: true
    #@ end

    #@overlay/match by=overlay.subset({"kind":"ConfigMap", "metadata": {"name":"istio","namespace":"istio-system"}}), expects=1
    ---
    data:
      #@overlay/replace via=lambda a,_: yaml.encode(overlay.apply(yaml.decode(a), custom_config()))
      mesh:
```
